### PR TITLE
Add Categorical Axis Ordering and Axis Category Array

### LINKED ISSUE #237: Add Categorical Axis ordering
Add the ability to configure Categorical Axis tick ordering to match with the Plotly library. I looked through the documentation and did not see any functionality that seems to do this.

See https://plotly.com/python/categorical-axes/#controlling-the-category-order-with-plotly-express

### PR DESCRIPTION
**Pull request by alex-bohm-nimbelink**
This adds Axis category ordering along with the Axis category array.

This should fix #237

### CODE REVIEW

**Comment by alex-bohm-nimbelink** [comment]
I'm not sure what kinds of tests or examples I should add? Is there anything I should focus on including?

**Comment by andrei-ng** [comment]
@alex-bohm-nimbelink , thank you for your PR!

If you could add an example either from your use case or something similar to the plots in https://plotly.com/python/categorical-axes/#controlling-the-category-order-with-plotly-express , it would be great. It would serve as an example for others to see how to make use of it.

In terms of tests, something along other existing tests, like serializing one plot with categorical axes, something like https://github.com/plotly/plotly.rs/blob/e0afa36503dcd3c302e60ee29541fd070c370759/plotly/src/traces/histogram.rs#L393 

Let me know if you need help with that .

**Comment by alex-bohm-nimbelink** [comment]
Thanks! I added some tests based off what other tests I see. I also added two examples.
A scatter plot with y axis categories:
image

A bar chart with x axis category sorting:
image

**Comment by andrei-ng** [comment]
> Thanks! I added some tests based off what other tests I see. I also added two examples. A scatter plot with y axis categories: image
> 
> A bar chart with x axis category sorting: image

Awesome ! 😍 
Thank your for your contribution! I will merge it in.

**Review by andrei-ng — APPROVED** [review]

**Pull request merged**
