### PR TITLE
build(deps): Depend on serde_with version 2 or 3

### PR DESCRIPTION
**Pull request by sjackman**
Depend on `serde_with` version 2 or 3.

### CODE REVIEW

**Review by andrei-ng — APPROVED** [review]

**Comment by sjackman** [comment]
Thank you for merging, Andrew! I'm excited to see this project reactivated. May I request a new stable release to Crates.io with these recently merged dependency updates when you have time?

**Comment by andrei-ng** [comment]
> Thank you for merging, Andrew! I'm excited to see this project reactivated. May I request a new stable release to Crates.io with these recently merged dependency updates when you have time?

Yes, this is the next step. @ndrezn , what is the status with crates.io permissions?

**Comment by ndrezn** [comment]
No update yet but I'll check in with Ioannis and get back to you shortly!

**Comment by andrei-ng** [comment]
@sjackman will try to do so this week. I am trying this week to merge all PRs that are API breaking before pushing a release.

**Pull request merged**
