### PR TITLE
Improve ergonomics of `Title` and `LegendGroupTitle` structs

### PR DESCRIPTION
**Pull request by fsktom**
A small quality of life improvement

So that instead of doing
```rust
let layout = Layout::new().title(format!("<b>{title}</b>").as_str().into());
```
I can now do
```rust
let layout = Layout::new().title(format!("<b>{title}</b>").into());
```

### CODE REVIEW

**Comment by fsktom** [comment]
This is even better! Thanks @mfreeborn :)

```rust
 let layout = Layout::new().title(format!("<b>{title}</b>"));
```
is even cleaner now :D

**Comment by fsktom** [comment]
I'm going to go ahead and try to fix the failing examples etc. if that's alright with you

**Comment by mfreeborn** [comment]
Yes, start going for it by all means! I ran out of time updating the remaining examples etc last night. I also intend to give `LegendGroupTitle` the same treatment, which we might as well do in this PR.
________________________________

**Comment by fsktom** [comment]
Glad to see the development of this project continuing <3

Decided to sync the changes of this PR with the main branch and adjust some things. Let me know what you think

**Comment by fsktom** [comment]
Seems like I missed some things... Now the clippy tests shouldn't fail

**Comment by andrei-ng** [comment]
> Glad to see the development of this project continuing <3
> 
> Decided to sync the changes of this PR with the main branch and adjust some things. Let me know what you think

Thanks for updating. Will have a look

**Review by andrei-ng — APPROVED** [review]

**Comment by andrei-ng** [comment]
@fsktom, thank you for fixing all the tests and clippy. I've just merged it.

**Comment by fsktom** [comment]
Thank you so much! :D

**Pull request merged**
